apiVersion: apps/v1
kind: Deployment
metadata:
  name: Golang-webserver
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: webserver
          image: ramya1507/webserver-v2
          ports:
            - containerPort: 80